-- AlterTable
ALTER TABLE "expenses" ADD COLUMN     "unit" DOUBLE PRECISION,
ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "incomes" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;
